apiVersion: apps/v1
kind: Deployment
metadata:
  name: wotapi
  labels:
    app: wotapi
spec:
  selector:
    matchLabels:
      app: wotapi
  template:
    metadata:
      labels:
        app: wotapi
    spec:
      containers:
      - name: wotapi
        image: stianfro/wotapi
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: wotapi
spec:
  selector:
    app: wotapi
  ports:
  - port: 8080
    targetPort: 8080
