basePath: /api/v1
definitions:
  models.Chapter:
    properties:
      id:
        description: ID is the chapter ID used to make it unique in the database
        type: string
      number:
        description: Number is the chapter number
        type: integer
      title:
        description: Title is the title of the chapter
        type: string
      volumeID:
        description: VolumeID is the volume ID that the chapter belongs to
        type: string
    type: object
  models.Manga:
    properties:
      author:
        description: Author is the author of the manga
        type: string
      id:
        description: ID is the manga ID used to make it unique in the database
        type: string
      magazine:
        description: Magazine is the magazine the manga was published in
        type: string
      publisher:
        description: Publisher is the publisher of the manga
        type: string
      title:
        description: Title is the title of the manga
        type: string
      volumes:
        description: Volumes is a slice of volumes
        items:
          $ref: '#/definitions/models.Volume'
        type: array
    required:
    - author
    - magazine
    - publisher
    - title
    type: object
  models.Volume:
    properties:
      chapters:
        description: Chapters is a slice of chapters
        items:
          $ref: '#/definitions/models.Chapter'
        type: array
      id:
        description: ID is the volume ID used to make it unique in the database
        type: string
      isbn:
        description: ISBN is the International Standard Book Number
        type: string
      mangaID:
        description: MangaID is the manga ID that the volume belongs to
        type: string
      number:
        description: Number is the volume number
        type: integer
      releaseDate:
        description: ReleaseDate is the date the volume was released
        type: string
      title:
        description: Title is the title of the volume
        type: string
    type: object
info:
  contact: {}
  description: This is a simple API that is used to demonstrate how to use Chi as
    a web framework.
  license:
    name: MIT
  title: Chi No Wadachi API
  version: 1.0.0
paths:
  /healthz:
    get:
      description: simple health check handler that returns 200 OK and is used for
        Kubernetes liveness probes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - health
  /manga:
    get:
      description: Lists all manga in the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Manga'
            type: array
      summary: List all manga
      tags:
      - manga
    post:
      consumes:
      - application/json
      description: Creates a manga in the database
      parameters:
      - description: Manga
        in: body
        name: manga
        required: true
        schema:
          $ref: '#/definitions/models.Manga'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Manga'
      summary: Create a manga
      tags:
      - manga
  /manga/{id}:
    get:
      description: Gets a manga from the database
      parameters:
      - description: Manga ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Manga'
      summary: Get a manga
      tags:
      - manga
  /manga/volume:
    post:
      consumes:
      - application/json
      description: Creates a volume in the database
      parameters:
      - description: Volume
        in: body
        name: volume
        required: true
        schema:
          $ref: '#/definitions/models.Volume'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Volume'
      summary: Create a volume
      tags:
      - volume
swagger: "2.0"
