basePath: /api/v1
info:
  contact: {}
  description: This is a simple API that is used to demonstrate how to use Chi as
    a web framework.
  license:
    name: MIT
  title: Chi No Wadachi API
  version: 1.0.0
paths: {}
swagger: "2.0"
